-- AlterTable
ALTER TABLE "seller_profile" ADD COLUMN     "bannerImage" TEXT,
ADD COLUMN     "companyName" TEXT,
ADD COLUMN     "discordUrl" TEXT,
ADD COLUMN     "facebookUrl" TEXT,
ADD COLUMN     "followerCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "instagramUrl" TEXT,
ADD COLUMN     "location" TEXT,
ADD COLUMN     "longDescription" TEXT,
ADD COLUMN     "responseTime" TEXT,
ADD COLUMN     "returnPolicy" TEXT,
ADD COLUMN     "shippingCountries" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "shippingTime" TEXT,
ADD COLUMN     "shopRules" TEXT,
ADD COLUMN     "shortDescription" TEXT,
ADD COLUMN     "website" TEXT,
ADD COLUMN     "youtubeUrl" TEXT;
